root_project: "/content/drive/Shareddrives/BOLSA_2026/a_bolsa2026_gemini"

paths:
  data_raw:         "00_data/01_raw"
  data_processed:   "00_data/02_processed"
  data_final:       "00_data/03_final"
  nb_prototyping:   "01_notebooks/prototyping"
  nb_analysis:      "01_notebooks/analysis"
  nb_modeling:      "01_notebooks/modeling"
  src:              "02_src"
  kb:               "03_knowledge_base"
  models:           "04_outputs/models"
  reports:          "04_outputs/reports"
  figures:          "04_outputs/figures"
  checkpoints:      "05_checkpoints"
